### ISSUE TITLE
line 254 error

### ISSUE THREAD

**Issue by wen-ye-xwz** [tsinghua-fib-lab/Spatio-temporal-Diffusion-Point-Processes#3]
Hi! It seems that I always get

Traceback (most recent call last):
  File "Spatio-temporal-Diffusion-Point-Processes/app.py", line 254, in <module>
    assert real.shape == sampled_seq_temporal_all.shape
AttributeError: 'list' object has no attribute 'shape'

In line 257 and 267, the two variables does not seem to be defined either. (mae_spatial_mean, rmse_temporal_mean)

when I try to run the script. It would be great if you could fix that. Thank you!

**Comment by YuanYuan98** [comment]
``sampled_seq_temporal_all`` is just for additional testing in my own experiments. I have updated ``app.py``, please refer to it again.

**Comment by Jiamin-Qiu** [comment]
Hello, may I ask why the Crime data has not been processed and run.
I would appreciate it if you could let me know.

**Comment by YuanYuan98** [comment]
I have uploaded the Crime dataset. The original data can be obtained via the [Atlanta Police Department](https://opendata.atlantapd.org).

**Comment by Jiamin-Qiu** [comment]
> 我已经上传了犯罪数据集。原始数据可以通过[亚特兰大警察局](https://opendata.atlantapd.org)获得。

Thank you very much.
