### ISSUE TITLE
About data rescaling

### ISSUE THREAD

**Issue by AnthonyChouGit** [tsinghua-fib-lab/Spatio-temporal-Diffusion-Point-Processes#4]
According to the change-of-variable formula of probability theory, different data scales can lead to different NLL values. It seems that the NLL results given in Table 2 are calculated under different data scales. I read your code and found that you normalize the (tau, lat, lng) triples to [-1, 1], which makes the diffusion more stable. However, some of the NLL results of your baseline models might have been calculated with different data normalization. For example, the DeepSTPP spatial NLL 4.92 does not seem reasonable compared to DSTPP's 0.413.

Change-of-variable formula of probability theory:

$$
    \log \Bigl(F(\boldsymbol{x})\Bigr)=\log p(\boldsymbol{x}) - \log \Bigl|\det \frac{\partial F}{\partial\boldsymbol{x}}\Bigr|
$$

**Comment by YuanYuan98** [comment]
Thanks very much for bringing up this important point! Data normalization can indeed affect log-likelihood calculations, introducing a constant term difference related to the scale of normalization.

After re-calculating the NLL values with considering the scale, the conclusion that DSTPP outperforms baselines still holds. It's important to note that the prediction results are not influenced by the data normalization issues. 

We appreciate your question, as it has helped us make our work more rigorous.
